AWSTemplateFormatVersion: "2010-09-09"
Description: Bucket S3 + Lambda acionada ao receber CSV

Resources:
  ## 1. Bucket S3
  MeuBucketCSV:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: meu-bucket-csv-processamento
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".csv"
            Function: !GetAtt ProcessaCSVLambda.Arn

  ## 2. Função Lambda para processar CSV
  ProcessaCSVLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: processa-csv-lambda
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import csv

          def lambda_handler(event, context):
              s3 = boto3.client('s3')
              
              # Pega o bucket e o arquivo do evento
              bucket = event['Records'][0]['s3']['bucket']['name']
              key = event['Records'][0]['s3']['object']['key']
              
              print(f"Novo arquivo recebido: s3://{bucket}/{key}")
              
              # Faz download do CSV
              response = s3.get_object(Bucket=bucket, Key=key)
              linhas = response['Body'].read().decode('utf-8').splitlines()
              reader = csv.reader(linhas)
              
              for row in reader:
                  print(row)  # aqui você processa cada linha

              return {"status": "sucesso", "arquivo": key}

  ## 3. Role de execução da Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-execution-role-processa-csv
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  ## 4. Permissão para S3 invocar a Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProcessaCSVLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt MeuBucketCSV.Arn
